export interface SubmitButtonProps {
    label: string;
    variant: 'primary' | 'secondary';
}

const VARIANT_CLASS: Record<SubmitButtonProps['variant'], string> = {
    primary: 'bg-blue-600 text-white hover:bg-blue-500',
    secondary: 'border border-slate-300 bg-white text-slate-700 hover:bg-slate-50',
};

export const actionComponents = {
    SubmitButton: {
        label: 'Submit Button',
        fields: {
            label: { type: 'text' as const, label: 'Button label' },
            variant: {
                type: 'select' as const,
                label: 'Style',
                options: [
                    { label: 'Primary (filled)', value: 'primary' },
                    { label: 'Secondary (outline)', value: 'secondary' },
                ],
            },
        },
        defaultProps: {
            label: 'Submit',
            variant: 'primary',
        },
        // `props` is intentionally left untyped here (rather than annotated
        // as `SubmitButtonProps`) and narrowed via a cast instead. Puck's own
        // `Config` type - when not threaded through with an explicit
        // per-component generic - expects `render` to accept a loosely
        // typed `{ [x: string]: any }`-ish object; annotating the parameter
        // itself with our narrower interface makes TypeScript reject the
        // assignment (a stricter parameter type isn't assignable where a
        // looser one is expected). Casting inside the function body gets us
        // the same type safety without fighting that contravariance check.
        render: (props: unknown) => {
            const { label, variant } = props as SubmitButtonProps;
            return (
                // type="button" here: this render function also powers the design
                // canvas and the in-app "Preview" tab, neither of which have a real
                // submission handler wired up. The code generated by "Export as
                // React Component" uses type="submit" with a real onSubmit handler.
                <button
                    type="button"
                    className={`inline-flex w-fit items-center justify-center rounded-md px-4 py-2 text-sm font-medium shadow-sm transition-colors focus:outline-none focus:ring-2 focus:ring-blue-500/40 ${VARIANT_CLASS[variant] || VARIANT_CLASS.primary}`}
                >
                    {label}
                </button>
            );
        },
    },
};
